DROP TABLE VETERINARIOS IF EXISTS;

CREATE TABLE VETERINARIOS(
ID INT AUTO_INCREMENT PRIMARY KEY,
NUMEROLICENCIA VARCHAR(15) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR(50) NOT NULL,
ESPECIALIDAD VARCHAR(50) NOT NULL
);

INSERT INTO VETERINARIOS VALUES (DEFAULT, 'TPSR456813', 'ALBERTO', 'TRUJILLO', 'PORCINOS');